### ISSUE TITLE
Are the Contents licensed under a CC BY-SA 3.0?

### ISSUE THREAD

**Issue by 0xis-cn** [lyczwy/New#1]
As those You published on Wikiversity.

**Comment by lyczwy** [comment]
Hello.&nbsp;I'm the original author. I don't know if I need a license. There are no licensing issues at Wikiversity.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyczwy/New"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 中午12:39
收件人:&nbsp;"lyczwy/New"<New@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lyczwy/New] Are the Contents licensed under a CC BY-SA 3.0? (#1)





 
As those You published on Wikiversity.
